### ISSUE TITLE
[Bug]: Windows 10 Angular ngc problem

### ISSUE THREAD

**Issue by kayla-32** [aspect-build/bazel-examples#195]
### What happened?

I was looking at this repo [https://github.com/jbedard/bazel-examples/tree/angular-ngc](url) (forked from aspect-build/bazel-examples) and decided to try out the angular-ngc example.

After cloning the repo and using the angular-ngc branch, I ran:
`bazel build //... -enable_runfiles`

and got the following output:
`INFO: Build option --enable_runfiles has changed, discarding analysis cache.
INFO: Analyzed 66 targets (31 packages loaded, 2387 targets configured).
INFO: Found 66 targets...
ERROR: C:/users/kayla/documents/angular/bazel-examples/angular-ngc/tools/BUILD.bazel:12:11: TsValidateOptions tools/_validate_ngc.esbuild_options.optionsvalid.d.ts failed: (Exit 1): validator.bat failed: error executing command bazel-out\x64_windows-opt-exec-2B5CBBC6\bin\external\npm_typescript\validator.bat tsconfig.node.json tools/_validate_ngc.esbuild_options.optionsvalid.d.ts //tools:ngc.esbuild ... (remaining 1 argument skipped)     
FATAL: aspect_rules_js[js_binary]: node wrapper '/c/Users/Kayla/AppData/Roaming/SPB_Data/_bazel_Kayla/t5plpeen/execroot/__main__/bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/npm_typescript/validator.bat.runfiles/__main__/../npm_typescript/validator_node_wrapper/node.bat' is not executable
INFO: Elapsed time: 25.804s, Critical Path: 6.93s
INFO: 276 processes: 199 internal, 77 local.
FAILED: Build did NOT complete successfully`

When using MacOS, `bazel build //...` runs with no issues and the Build is successful. On the other hand, when I try it out on Windows 10 with the 'enable_runfiles' flag, it outputs the above error (the 'enable_runfiles' flag is needed on Windows machines to provide support for rules_js). I'm thinking the error is Windows specific then?

### Version

Development (host) and target OS/architectures: Windows 10

Output of `bazel --version`: bazel 5.3.0 

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: NA

Language(s) and/or frameworks involved: NA

### How to reproduce

```shell
git clone https://github.com/jbedard/bazel-examples.git

Under angular-ngc branch do the following:
cd bazel-examples/angular-ngc
bazel build //... --enable_runfiles
```

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
Thanks for the issue. From the callstack it looks like the issue is coming from the rules_ts tsconfig validator. Unfortunately we don't use Windows ourselves for development and don't currently have any clients using Windows to fund Windows work in rules_js and derivate rules.

My recommendation in general is to use WSL (Windows Linux Subsystem) when building with Bazel on Windows. From past experience this is much easier than dealing with Windows issues across the Bazel ecosystem (many rules have issues since Windows is not commonly used with Bazel and rules don't have Windows CI so regressions can occur easily). Performance tends be as good or faster with WSL as well.

**Comment by kayla-32** [comment]
noted! Thanks for the insight and recommendation!
