### ISSUE TITLE
[Question] How do I optimise for build speed with ng_lib?

### ISSUE THREAD

**Issue by mtsgrd** [aspect-build/bazel-examples#209]
Hey,

Before I attempt switching from `rules_nodejs` to `rules_js` I would like to understand the recommended granularity of `ng_lib` for rebuilding my app.

The provided angular-ngc example splits out a common component and a common lib, but I'm currently only building one app. I would still like to optimise for build speed, for the sake of quick iterations.

So I think I'm asking if it would make sense to have one `ng_lib` per component in my project?

Thanks!

**Comment by jbedard** [comment]
It should be no different then `rules_nodejs`, what did you decide there? I think that's a more general bazel question though and not specific to any framework or ruleset.

I've often done one BUILD per ng module because those modules seemed like a reasonable size but that could depend how you structure your modules 🤷 

But questions like this would be better discussed somewhere like bazel slack (https://bazelbuild.slack.com/archives/CULGHFKCK) so I'm going to close this.
